import Link from "next/link";
import { notFound } from "next/navigation";
import { requirePageActor } from "@/lib/auth/authorization";
import { getAccountDetail } from "@/lib/data/crm-details";
import { AccountEditForm } from "@/components/crm-forms";
import { stageLabel } from "@/lib/crm/catalog";

export default async function AccountDetailPage({params}:{params:Promise<{accountId:string}>}) {
  const actor=await requirePageActor(); const {accountId}=await params; const account=await getAccountDetail(accountId); if(!account)notFound();
  return <main className="app-shell"><div className="container"><Link className="back-link mono" href="/accounts">← Accounts</Link><header className="page-header"><div><p className="mono">Account · {account.archived_at?"Archived":"Active"}</p><h1 className="page-title">{account.name}</h1><p className="subtitle">Owned CRM workspace with related contacts, opportunities, and activity history.</p></div></header><AccountEditForm account={account} editable={account.owner_user_id===actor.id}/><div className="workflow-grid"><section><div className="section-title"><span className="mono">01</span><h2>Contacts</h2></div>{account.contacts.length?<div className="stack">{account.contacts.map(c=><Link className="card row-card" href={`/contacts/${c.id}`} key={c.id}><div><strong>{c.first_name} {c.last_name}</strong><p>{c.job_title??c.email??"No contact details"}</p></div><span>→</span></Link>)}</div>:<div className="empty-state"><h2>No contacts</h2><p>The account owner can add its first stakeholder from Accounts.</p></div>}</section><section><div className="section-title"><span className="mono">02</span><h2>Opportunities</h2></div>{account.opportunities.length?<div className="stack">{account.opportunities.map(o=><Link className="card row-card" href={`/deals/${o.id}`} key={o.id}><div><strong>{o.name}</strong><p>{stageLabel(o.stage)} · AED {Number(o.value_amount).toLocaleString("en-AE")}</p></div><span>→</span></Link>)}</div>:<div className="empty-state"><h2>No opportunities</h2><p>Create the first qualified opportunity from Pipeline.</p></div>}</section></div><section><div className="section-title"><span className="mono">03</span><h2>Activity timeline</h2></div>{account.activities.length?<div className="stack">{account.activities.map(a=><article className="card row-card" key={a.id}><span className="chip">{a.kind.replace("_"," ")}</span><div><strong>{a.subject}</strong><p>{a.status} · {a.priority}{a.due_at?` · due ${new Intl.DateTimeFormat("en-AE",{dateStyle:"medium"}).format(new Date(a.due_at))}`:""}</p></div></article>)}</div>:<div className="empty-state"><h2>No activity yet</h2><p>Linked tasks, follow-ups, calls, emails, and notes will appear here.</p></div>}</section></div></main>;
}

